### ISSUE TITLE
Add mowpod

### ISSUE THREAD

**Issue by kookster** [PRX/prx-podagent#37]
Like the prx webplayer, comes in via a _from value, so something like:

```
  - regex: '^mowpod\.com'
    name: mowPod
    notes:
      - mowPod web player as _from query string
    examples:
      - mowpod.com
```
